---
- name: Setup Kubernetes Cluster
  hosts: k8s_cluster
  become: yes
  roles:
    - kubernetes-prerequisites

- name: Setup GPU Prerequisites
  hosts: gpu_workers
  become: yes
  roles:
    - gpu-prerequisites

- name: Initialize Control Plane
  hosts: control_plane
  become: yes
  roles:
    - kubernetes-control-plane

- name: Join Worker Nodes
  hosts: workers:gpu_workers
  become: yes
  roles:
    - kubernetes-worker

- name: Label GPU Nodes
  hosts: gpu_workers
  become: yes
  roles:
    - gpu-node-labeling

- name: Install Argo CD
  hosts: control_plane
  become: yes
  roles:
    - argocd

- name: Install MetalLB
  hosts: control_plane
  become: yes
  roles:
    - metallb

- name: Install Ray Operator
  hosts: control_plane
  become: yes
  roles:
    - ray-operator

- name: Install NVIDIA Device Plugin
  hosts: control_plane
  become: yes
  roles:
    - nvidia-device-plugin

- name: Install MinIO
  hosts: control_plane
  become: yes
  roles:
    - minio

- name: Setup USB Storage on Worker Nodes
  hosts: workers
  become: yes
  roles:
    - usb-storage

- name: Configure USB Storage in Kubernetes
  hosts: control_plane
  become: yes
  roles:
    - usb-storage-k8s
