---
- name: Deploy SSH Keys
  hosts: k8s_cluster
  become: yes
  tags:
    - ssh-keys
  roles:
    - ssh-keys

- name: Setup Kubernetes Cluster
  hosts: k8s_cluster
  become: yes
  tags:
    - prerequisites
  roles:
    - kubernetes-prerequisites

- name: Setup GPU Prerequisites
  hosts: gpu_workers
  become: yes
  tags:
    - gpu-prerequisites
  roles:
    - gpu-prerequisites

- name: Initialize Control Plane
  hosts: control_plane
  become: yes
  tags:
    - control-plane
  roles:
    - kubernetes-control-plane

- name: Fetch Kubeconfig
  hosts: control_plane
  become: yes
  tags:
    - fetch-kubeconfig
    - kubeconfig
  roles:
    - fetch-kubeconfig

- name: Join Worker Nodes
  hosts: workers:gpu_workers
  become: yes
  tags:
    - workers
  roles:
    - kubernetes-worker

- name: Label GPU Nodes
  hosts: gpu_workers
  become: yes
  tags:
    - gpu-labeling
  roles:
    - gpu-node-labeling

- name: Install Argo CD
  hosts: control_plane
  become: yes
  tags:
    - argocd
  roles:
    - argocd

- name: Install MetalLB
  hosts: control_plane
  become: yes
  tags:
    - metallb
  roles:
    - metallb

- name: Install Sealed Secrets
  hosts: control_plane
  become: yes
  tags:
    - sealed-secrets
    - secrets
  roles:
    - sealed-secrets

- name: Install Metrics Server
  hosts: control_plane
  become: yes
  tags:
    - metrics-server
    - metrics
  roles:
    - metrics-server

- name: Install Ray Operator
  hosts: control_plane
  become: yes
  tags:
    - ray
  roles:
    - ray-operator

- name: Install NVIDIA Device Plugin
  hosts: control_plane
  become: yes
  tags:
    - gpu-plugin
  roles:
    - nvidia-device-plugin

- name: Install MinIO
  hosts: control_plane
  become: yes
  tags:
    - minio
  roles:
    - minio

- name: Expose Services via LoadBalancer
  hosts: control_plane
  become: yes
  tags:
    - expose-services
    - loadbalancer
  roles:
    - expose-services

- name: Setup USB Storage on Worker Nodes
  hosts: workers
  become: yes
  tags:
    - usb-storage
  roles:
    - usb-storage

- name: Configure USB Storage in Kubernetes
  hosts: control_plane
  become: yes
  tags:
    - usb-storage
  roles:
    - usb-storage-k8s
